name: Update GitHub Radar

on:
  schedule:
    # 每天 UTC 时间 16:00 运行（对应北京时间 0:00）
    - cron: '0 16 * * *'
  workflow_dispatch: # 允许手动点击按钮立即运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        env:
          # 从 GitHub Secrets 中读取 Token
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: python utils/CommitTimeRadar.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add imgs/github_commit_radar.png
          # 检查是否有实际变更
          if ! git diff --quiet --cached; then
            git commit -m "Update Radar Chart [$(date -u)]"

            # 拉取远程最新变更并 rebase 当前提交
            git pull --rebase origin main

            # 推送（如果 rebase 成功）
            git push origin main
          else
            echo "No changes detected. Skipping commit."
          fi
